### ISSUE TITLE
Inquiry about Submission Status

### ISSUE THREAD

**Issue by XiaolongTang23** [interaction-dataset/interaction-dataset#26] opened 2023-12-25 08:20 UTC
I recently submitted my results to the INTERACTION dataset, but I have encountered an issue.    Despite the submission, there appears to be no record of it, and my results are not reflected on the leaderboard.

Could you kindly assist me in understanding the following:

1.   Is there a typical delay in updating the submission records and the leaderboard?
2.   Are there any common issues or specific requirements I might have missed during the submission process?
3.   Could you please provide guidance on how I can confirm if my submission was successful, or if necessary, how to correctly resubmit?

**Comment by ChengkaiYang** [comment] 2023-12-28 07:42
> I recently submitted my results to the INTERACTION dataset, but I have encountered an issue. Despite the submission, there appears to be no record of it, and my results are not reflected on the leaderboard.
> 
> Could you kindly assist me in understanding the following:
> 
> 1. Is there a typical delay in updating the submission records and the leaderboard?
> 2. Are there any common issues or specific requirements I might have missed during the submission process?
> 3. Could you please provide guidance on how I can confirm if my submission was successful, or if necessary, how to correctly resubmit?

I have met the same problem.Have you fixed the problem?I got no answer for three weeks.

**Comment by william-gx** [comment] 2024-01-25 11:30
Similar problem. Looking forward to the response. Thx.

**Comment by m-naumann** [comment] 2024-02-23 07:59
@ZHAN-Wei @litingsun can you help out?

**Comment by kkk00714** [comment] 2024-02-23 08:36
> > I recently submitted my results to the INTERACTION dataset, but I have encountered an issue. Despite the submission, there appears to be no record of it, and my results are not reflected on the leaderboard.
> > Could you kindly assist me in understanding the following:
> > 
> > 1. Is there a typical delay in updating the submission records and the leaderboard?
> > 2. Are there any common issues or specific requirements I might have missed during the submission process?
> > 3. Could you please provide guidance on how I can confirm if my submission was successful, or if necessary, how to correctly resubmit?
> 
> I have met the same problem.Have you fixed the problem?I got no answer for three weeks.

I also met the same problem. Have you succeeded to get the reflection? Thanks for any response.

**Comment by kkk00714** [comment] 2024-02-23 08:43
> @ZHAN-Wei @litingsun can you help out?

Hello, it has been more than a week since I submitted the result and I have not received any reply. Could you help me solve this problem? I noticed that the latest submission result on the leaderboard was January 4th. Is there any delay in updating the leaderboard?

**Comment by XiaolongTang23** [comment] 2024-02-24 09:45
> > > I recently submitted my results to the INTERACTION dataset, but I have encountered an issue. Despite the submission, there appears to be no record of it, and my results are not reflected on the leaderboard.
> > > Could you kindly assist me in understanding the following:
> > > 
> > > 1. Is there a typical delay in updating the submission records and the leaderboard?
> > > 2. Are there any common issues or specific requirements I might have missed during the submission process?
> > > 3. Could you please provide guidance on how I can confirm if my submission was successful, or if necessary, how to correctly resubmit?
> > 
> > 
> > I have met the same problem.Have you fixed the problem?I got no answer for three weeks.
> 
> I also met the same problem. Have you succeeded to get the reflection? Thanks for any response.

Unfortunately, I still haven't received any feedback.

**Comment by parham-sharaf** [comment] 2024-02-25 21:34
Try to resubmit your files. We were experiencing issues with the back-end. Make sure you select the agent type before submitting your file.

**Comment by kkk00714** [comment] 2024-02-26 07:42
> Try to resubmit your files. We were experiencing issues with the back-end. Make sure you select the agent type before submitting your file.

Thank you! I have succeed to get the feedback. But the leaderboard shows that all metrics of my method are 0. I double-checked my files and didn't find any problems. Can you tell me what the problem is?

**Comment by kkk00714** [comment] 2024-02-26 08:22
![image](https://github.com/interaction-dataset/interaction-dataset/assets/75302401/830c9221-065e-4ba6-a16f-e2d32411ff58)
You may still have problems with your back-end, my data and the data you used for test have the same metrics as seneva_means.

**Comment by kkk00714** [comment] 2024-02-26 10:14
@parham-sharaf It seems that all four tracks are experiencing the same problem. Latest method of conditional single-agent shows same results.
![20240226181409](https://github.com/interaction-dataset/interaction-dataset/assets/75302401/f4adb5d6-7955-485c-88d0-9996f2716bda)

**Comment by parham-sharaf** [comment] 2024-02-27 11:42
the bug should be fixed now. I have added a new feature where you should receive an email upon each submission that contains all the results of the file uploaded. Please let me know if you are still running into issues.

**Comment by parham-sharaf** [comment] 2024-02-27 20:43
please don't spam submissions. wait until you receive the email for your submission. The system is down momentarily.

**Comment by kkk00714** [comment] 2024-02-27 20:46
> the bug should be fixed now. I have added a new feature where you should receive an email upon each submission that contains all the results of the file uploaded. Please let me know if you are still running into issues.

I'm sorry for this, because I didn't get feedback when I submitted a pure gen type file, so I tried something else.

**Comment by parham-sharaf** [comment] 2024-03-03 22:06
The website should be up. Feel free to do your submissions. Please let me know if you are encountering any issues

**Comment by XiaolongTang23** [comment] 2024-03-19 15:07
> > Try to resubmit your files. We were experiencing issues with the back-end. Make sure you select the agent type before submitting your file.
> 
> Thank you! I have succeed to get the feedback. But the leaderboard shows that all metrics of my method are 0. I double-checked my files and didn't find any problems. Can you tell me what the problem is?
Hi, I had the same problem. How did you solve it?

**Comment by XiaolongTang23** [comment] 2024-03-19 15:07
> > Try to resubmit your files. We were experiencing issues with the back-end. Make sure you select the agent type before submitting your file.
> 
> Thank you! I have succeed to get the feedback. But the leaderboard shows that all metrics of my method are 0. I double-checked my files and didn't find any problems. Can you tell me what the problem is?

Hi, I had the same problem. How did you solve it? Thanks for any response.

**Comment by parham-sharaf** [comment] 2024-03-19 18:35
> > > Try to resubmit your files. We were experiencing issues with the back-end. Make sure you select the agent type before submitting your file.
> > 
> > 
> > Thank you! I have succeed to get the feedback. But the leaderboard shows that all metrics of my method are 0. I double-checked my files and didn't find any problems. Can you tell me what the problem is?
> 
> Hi, I had the same problem. How did you solve it? Thanks for any response.

Are you still experiencing this issue? If so, email parham-sharaf@berkeley.edu so I can resolve your issue and further investigate the cause of that matter.

**Comment by kkk00714** [comment] 2024-03-19 18:43
> > > > Try to resubmit your files. We were experiencing issues with the back-end. Make sure you select the agent type before submitting your file.
> > > 
> > > 
> > > Thank you! I have succeed to get the feedback. But the leaderboard shows that all metrics of my method are 0. I double-checked my files and didn't find any problems. Can you tell me what the problem is?
> > 
> > 
> > Hi, I had the same problem. How did you solve it? Thanks for any response.
> 
> Are you still experiencing this issue? If so, email [parham-sharaf@berkeley.edu](mailto:parham-sharaf@berkeley.edu) so I can resolve your issue and further investigate the cause of that matter.

It seems that the problem still exists in the multi-agent tracks.

**Comment by parham-sharaf** [comment] 2024-03-19 18:45
> > > > > Try to resubmit your files. We were experiencing issues with the back-end. Make sure you select the agent type before submitting your file.
> > > > 
> > > > 
> > > > Thank you! I have succeed to get the feedback. But the leaderboard shows that all metrics of my method are 0. I double-checked my files and didn't find any problems. Can you tell me what the problem is?
> > > 
> > > 
> > > Hi, I had the same problem. How did you solve it? Thanks for any response.
> > 
> > 
> > Are you still experiencing this issue? If so, email [parham-sharaf@berkeley.edu](mailto:parham-sharaf@berkeley.edu) so I can resolve your issue and further investigate the cause of that matter.
> 
> It seems that the problem still exists in the multi-agent tracks.

on the email reply you get, does it show the result was successful or not? it should be the last key in the json file that gets emailed to you

**Comment by kkk00714** [comment] 2024-03-19 18:56
@XiaolongTang23 

> > > Try to resubmit your files. We were experiencing issues with the back-end. Make sure you select the agent type before submitting your file.
> > 
> > 
> > Thank you! I have succeed to get the feedback. But the leaderboard shows that all metrics of my method are 0. I double-checked my files and didn't find any problems. Can you tell me what the problem is?
> 
> Hi, I had the same problem. How did you solve it? Thanks for any response.

@XiaolongTang23

**Comment by XiaolongTang23** [comment] 2024-03-20 01:19
> > > > > > Try to resubmit your files. We were experiencing issues with the back-end. Make sure you select the agent type before submitting your file.
> > > > > 
> > > > > 
> > > > > Thank you! I have succeed to get the feedback. But the leaderboard shows that all metrics of my method are 0. I double-checked my files and didn't find any problems. Can you tell me what the problem is?
> > > > 
> > > > 
> > > > Hi, I had the same problem. How did you solve it? Thanks for any response.
> > > 
> > > 
> > > Are you still experiencing this issue? If so, email [parham-sharaf@berkeley.edu](mailto:parham-sharaf@berkeley.edu) so I can resolve your issue and further investigate the cause of that matter.
> > 
> > 
> > It seems that the problem still exists in the multi-agent tracks.
> 
> on the email reply you get, does it show the result was successful or not? it should be the last key in the json file that gets emailed to you

["message": "DR_USA_Roundabout_SR_sub.csv: [ErrNotFound: not found]<br>DR_USA_Intersection_EP0_sub.csv: [ErrNotFound: not found]<br>DR_USA_Roundabout_FT_sub.csv: [ErrNotFound: not found]<br>DR_USA_Intersection_EP1_sub.csv: [ErrNotFound: not found]<br>DR_USA_Intersection_MA_sub.csv: [ErrNotFound: not found]<br>DR_CHN_Merging_ZS0_sub.csv: [ErrNotFound: not found]<br>DR_USA_Roundabout_EP_sub.csv: [ErrNotFound: not found]<br>DR_CHN_Merging_ZS2_sub.csv: [ErrNotFound: not found]<br>DR_USA_Intersection_GL_sub.csv: [ErrNotFound: not found]<br>DR_LaneChange_ET1_sub.csv: [ErrNotFound: not found]<br>DR_LaneChange_ET0_sub.csv: [ErrNotFound: not found]<br>DR_Merging_TR1_sub.csv: [ErrNotFound: not found]<br>DR_Intersection_CM_sub.csv: [ErrNotFound: not found]<br>DR_DEU_Roundabout_OF_sub.csv: [ErrNotFound: not found]<br>DR_DEU_Merging_MT_sub.csv: [ErrNotFound: not found]<br>DR_Merging_TR0_sub.csv: [ErrNotFound: not found]<br>DR_Roundabout_RW_sub.csv: [ErrNotFound: not found]",
"success": false"]
That's the result. Each file is in the zip file, So I don't know how to solve this problem.

**Comment by parham-sharaf** [comment] 2024-03-20 08:01
@XiaolongTang23 The backend seems to be working fine. I just uploaded a test file to see if there is a problem with the evaluation. It went through fine. Let me bring this issue to Dr. Zhan's attention. I believe it's with how you are formatting the csv files or if you are missing certain columns

**Comment by XiaolongTang23** [comment] 2024-03-20 11:22
> @XiaolongTang23 The backend seems to be working fine. I just uploaded a test file to see if there is a problem with the evaluation. It went through fine. Let me bring this issue to Dr. Zhan's attention. I believe it's with how you are formatting the csv files or if you are missing certain columns

Thank you! I noticed that the csv files are missing some rows. I re-generated the results and submitted them about two hours ago, but I don't have received email feedback, and there are no results on the leaderboard. Can you help me with that?

**Comment by XiaolongTang23** [comment] 2024-03-21 08:24
> @XiaolongTang23 The backend seems to be working fine. I just uploaded a test file to see if there is a problem with the evaluation. It went through fine. Let me bring this issue to Dr. Zhan's attention. I believe it's with how you are formatting the csv files or if you are missing certain columns

Thank you again! All my problems have been solved and I can see the results on the leaderboard.

**Closed as completed** 2024-03-21 08:24 UTC

**Comment by chenx1e** [comment] 2025-04-30 19:31
Hello, this problem seems to happen again. I uploaded the test set results of the multi-agent task, but I haven't received any feedback regarding the performance, and it also does not reflect on the leaderboard. The latest uploaded time on the website is March 13th. Could anyone help out? Thank you all!! @parham-sharaf @kkk00714 @XiaolongTang23 @m-naumann 

> > [@ZHAN-Wei](https://github.com/ZHAN-Wei) [@litingsun](https://github.com/litingsun) can you help out?
> 
> Hello, it has been more than a week since I submitted the result and I have not received any reply. Could you help me solve this problem? I noticed that the latest submission result on the leaderboard was January 4th. Is there any delay in updating the leaderboard?

**Comment by kkk00714** [comment] 2025-06-18 18:47
@parham-sharaf, please help check the leaderboard. Thank you!
